CREATE TABLE DIVISION_DECIMAL (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NUMERO_A NUMBER(10,4),
NUMERO_B NUMBER(10,4),
RESULTADO NUMBER(10,4),
FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;
-- sp sp_insertar_division : .
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DIVISION (
P_A IN NUMBER,
P_B IN NUMBER,
P_RESULTADO IN NUMBER
) AS
BEGIN
INSERT INTO DIVISION_DECIMAL (NUMERO_A, NUMERO_B, RESULTADO)
VALUES (P_A, P_B, P_RESULTADO);
COMMIT;
END;
/

COMMIT;